<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [3]:
import numpy as np
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
greet = greeting(name="''")
greet

"Hello ''!"

In [6]:
greet = greeting(name="Batman")
greet

'Hello Batman! So, nice to meet you!'

In [5]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()
list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])
list_min, list_max, list_mean

(1, 5, 3.0)

### 1.2 Named functions that don’t return

In [1]:
print("sadge again")

sadge again


### 1.3 Anonymous functions

In [10]:
my_short_function = lambda name: f"Hello {name}!"
my_short_function(name="Super Man")

numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers) 

sorted(numbers, key=lambda x: x[1]) #second element


[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

### 1.4 Optional arguments

In [19]:
def greeting(name='no one', times = 3):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you! '*times
    else:
        return f'Hello {name}! '*times

print('I', 'am', 'Batman!', sep='.')
greeting()


I.am.Batman!


'Hello no one! Hello no one! Hello no one! '

## 2 The importance of functions?

### 2.1 An argument for functions

Hide stuff you don't need or something

### 2.2 A word of caution

Functions can be overused/misused

## Exercise 1 :  Do you know why?

``return`` exits the function with the corresponding value.

If the ``if`` statement evalutes to true, the first ``return`` will be executed else the function moves to the second ``return`` line.

## Exercise 2 :  Calculator functions

In [4]:
def add(x,y):
    return x+y
def subtract(x,y):
    return x-y
def multiply(x,y):
    return x*y
def divide(x,y):
    if np.all(y):
        return x/y
    else:
        return None #I'm not a quitter
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
add(x,y), subtract(x,y), multiply(x,y), divide(x,y), divide(x,y*0)

(array([100, 100, 100, 100, 100]),
 array([-28, -32, -12,  52, -46]),
 array([2304, 2244, 2464, 1824, 1971]),
 array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301]),
 None)

## Exercise 3 :  max_info() with NumPy

In [1]:
def max_info(numbers): #Min Xian's favourite function
    return np.max(numbers), np.argmax(numbers)
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]
max_info(numbers)

(83, 2)