<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [1]:
import numpy as np
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"}

### 1.2 Accessing data from a list (or array)

In [2]:
print(py_real_names[0:2])
print(py_super_names[-3:-1])

['Natasha Romanoff', 'Tony Stark']
['Black Widow', 'Iron Man']


### 1.3 Accessing data from a dictionary

In [3]:
print(superhero_info['Natasha Romanoff']) #you can hit Tab after '['
print(superhero_info.keys(), superhero_info.values())

Black Widow
dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange']) dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])


### 1.4 Higher dimensional lists

In [4]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]
py_superhero_info[1][1] #ugh

'Iron Man'

## 2 Lists vs. Arrays

### 2.1 Size

In [5]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)
print(len(py_list_2d),len(np_array_2d),np_array_2d.shape) #shape is an attribute

10 10 (10, 2)


### 2.2 Arrays are fussy about type

In [6]:
py_list = [1, 1.5, 'A']
py_array = np.array(py_list)
print(py_list[0]+py_list[1])
print(py_array[0]+py_array[1]) #concatenation

2.5
11.5


### 2.3 Adding a number

In [7]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
#py_list + 10        # Won't work!
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [8]:
#so I won't need to keep creating the same variable
py_list_2 = [10, 20, 30, 40, 50]
np_array_2 = np.array(py_list_2)
py_list + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [9]:
np_array + np_array_2 #are you a vector?

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [10]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [11]:
np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [12]:
np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [13]:
py_list == [1,2,3] + [4,5] #fixed it #not work: py_list > 3 

True

In [20]:
print(np_array == 3 , np_array > 3)

[False False  True False False] [False False False  True  True]


### 2.8 Mathematics

In [23]:
print(sum(py_list), max(py_list), min(py_list)) #not work: py_list.sum()
print(np_array.sum(), np_array.mean(), np_array.max(), np_array.min())

15 5 1
15 3.0 5 1


## Exercise 1 :  Total recall?

1. Both lists and arrays can be iterated over, and both can store data in multiple dimensions.

2. With the + operator, lists are concatenated while arrays compute their sum pair-wise.
   Lists can contain elements of different dtypes, while arrays only have elements of a single dtype.
   
3. Dictionaries, declared with {}, store pairs of (keys, values) and are accessed via the unique keys.

## Exercise 2 :  Index me

In [24]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]

print(py_list[0:9:2])

['a1', 'c3', 'e5', 'g7', 'i9']


## Exercise 3 :  Capitalise Heros

In [28]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }
for i in superhero_info.keys():
    superhero_info[i] = superhero_info[i].upper()
superhero_info

{'Natasha Romanoff': 'BLACK WIDOW',
 'Tony Stark': 'IRON MAN',
 'Stephen Strange': 'DOCTOR STRANGE'}

## Exercise 4 :  How many ones

In [30]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]     
print(sum(np.array(numbers)==1))

9
