<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [3]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array
x[::-1] #倒数

array(['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1'],
      dtype='<U3')

### 1.2 Subsetting by masking (Arrays only)

In [7]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np_array > 3) #I hate dummy variables.
np_array[np_array > 3]


[False False False  True  True  True  True  True  True  True]


array([ 4,  5,  6,  7,  8,  9, 10])

In [24]:
np_array[~(np_array > 3)] #Numpy uses bitwise operator masks

array([1, 2, 3])

In [25]:
np_array[(np_array > 3) & (np_array < 8)] 

array([4, 5, 6, 7])

In [26]:
np_array[(np_array < 3) | (np_array > 8)]    

array([ 1,  2,  9, 10])

### 1.3 Indexing & Slicing 2D Lists

In [51]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]
py_list_2d[:3][0] #oh no, I can't access them all!
for a in py_list_2d[:3]:
    print(a[0])

1
2
3


[[1, 'A'], [2, 'B'], [3, 'C']]

### 1.4 Indexing & Slicing 2D Arrays

In [41]:
np_array_2d = np.array(py_list_2d)
np_array_2d[:3,0]

array(['1', '2', '3'], dtype='<U11')

### 1.5 Growing lists

In [62]:
x= [3]*4 + [5]*6 #my wifi password
x += [7]*8
x = [1]*2 + x
x

[1, 1, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 7, 7, 7, 7, 7, 7, 7, 7]

## 2 Some loose ends

### 2.1 Tuples

In [64]:
a=(1, 2, 3)
a[0] += [10]

TypeError: unsupported operand type(s) for +=: 'int' and 'list'

### 2.2 Be VERY careful when copying

In [68]:
x = [2]
y = x.copy()
y.append(3)
print(x)
z = x
x.append(1)
x,y,z

[2]


([2, 1], [2, 3], [2, 1])

## Exercise 1 :  Total recall?

Subsetting is the act of retrieving a subset of a list, array or tuple; i.e. all of the below.

Indexing retrieves a single element in a list, array or tuple.

Slicing retrieves a range of elements in a list, array or tuple.

Masking filters elements in a list, array or tuple using a truth statement.

## Exercise 2 :  Show me the ‘odd’ letters

In [84]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
np_array_2d[(np_array_2d[:,0].astype(int)%2 == 1),1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')